repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format


  - repo: local
    hooks:
      - id: run-smoke-test
        name: Run smoke test
        entry: pytest -s tests/smoke_test.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-commit ]
        require_serial: true
        fail_fast: false
        require_clean_working_dir: false

